// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.example.feature

/** Containers for sequential data.
  *
  * A FeatureList contains lists of Features.  These may hold zero or more
  * Feature values.
  *
  * FeatureLists are organized into categories by name.  The FeatureLists message
  * contains the mapping from name to FeatureList.
  */
@SerialVersionUID(0L)
final case class FeatureList(
    feature: _root_.scala.Seq[org.tensorflow.example.feature.Feature] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[FeatureList] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      feature.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      feature.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearFeature = copy(feature = _root_.scala.Seq.empty)
    def addFeature(__vs: org.tensorflow.example.feature.Feature*): FeatureList = addAllFeature(__vs)
    def addAllFeature(__vs: Iterable[org.tensorflow.example.feature.Feature]): FeatureList = copy(feature = feature ++ __vs)
    def withFeature(__v: _root_.scala.Seq[org.tensorflow.example.feature.Feature]): FeatureList = copy(feature = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => feature
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(feature.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = org.tensorflow.example.feature.FeatureList
    // @@protoc_insertion_point(GeneratedMessage[tensorflow.FeatureList])
}

object FeatureList extends scalapb.GeneratedMessageCompanion[org.tensorflow.example.feature.FeatureList] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.example.feature.FeatureList] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.example.feature.FeatureList = {
    val __feature: _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.example.feature.Feature] = new _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.example.feature.Feature]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __feature += _root_.scalapb.LiteParser.readMessage[org.tensorflow.example.feature.Feature](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.tensorflow.example.feature.FeatureList(
        feature = __feature.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.example.feature.FeatureList] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.tensorflow.example.feature.FeatureList(
        feature = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[org.tensorflow.example.feature.Feature]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = FeatureProto.javaDescriptor.getMessageTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = FeatureProto.scalaDescriptor.messages(5)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = org.tensorflow.example.feature.Feature
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.tensorflow.example.feature.FeatureList(
    feature = _root_.scala.Seq.empty
  )
  implicit class FeatureListLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.example.feature.FeatureList]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.example.feature.FeatureList](_l) {
    def feature: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[org.tensorflow.example.feature.Feature]] = field(_.feature)((c_, f_) => c_.copy(feature = f_))
  }
  final val FEATURE_FIELD_NUMBER = 1
  def of(
    feature: _root_.scala.Seq[org.tensorflow.example.feature.Feature]
  ): _root_.org.tensorflow.example.feature.FeatureList = _root_.org.tensorflow.example.feature.FeatureList(
    feature
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.FeatureList])
}
