// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.example.feature

/** @param featureList
  *   Map from feature name to feature list.
  */
@SerialVersionUID(0L)
final case class FeatureLists(
    featureList: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList] = _root_.scala.collection.immutable.Map.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[FeatureLists] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      featureList.foreach { __item =>
        val __value = org.tensorflow.example.feature.FeatureLists._typemapper_featureList.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      featureList.foreach { __v =>
        val __m = org.tensorflow.example.feature.FeatureLists._typemapper_featureList.toBase(__v)
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearFeatureList = copy(featureList = _root_.scala.collection.immutable.Map.empty)
    def addFeatureList(__vs: (_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList)*): FeatureLists = addAllFeatureList(__vs)
    def addAllFeatureList(__vs: Iterable[(_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList)]): FeatureLists = copy(featureList = featureList ++ __vs)
    def withFeatureList(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList]): FeatureLists = copy(featureList = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => featureList.iterator.map(org.tensorflow.example.feature.FeatureLists._typemapper_featureList.toBase(_)).toSeq
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(featureList.iterator.map(org.tensorflow.example.feature.FeatureLists._typemapper_featureList.toBase(_).toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = org.tensorflow.example.feature.FeatureLists
    // @@protoc_insertion_point(GeneratedMessage[tensorflow.FeatureLists])
}

object FeatureLists extends scalapb.GeneratedMessageCompanion[org.tensorflow.example.feature.FeatureLists] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.example.feature.FeatureLists] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.example.feature.FeatureLists = {
    val __featureList: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __featureList += org.tensorflow.example.feature.FeatureLists._typemapper_featureList.toCustom(_root_.scalapb.LiteParser.readMessage[org.tensorflow.example.feature.FeatureLists.FeatureListEntry](_input__))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.tensorflow.example.feature.FeatureLists(
        featureList = __featureList.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.example.feature.FeatureLists] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.tensorflow.example.feature.FeatureLists(
        featureList = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[org.tensorflow.example.feature.FeatureLists.FeatureListEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(org.tensorflow.example.feature.FeatureLists._typemapper_featureList.toCustom(_)).toMap
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = FeatureProto.javaDescriptor.getMessageTypes().get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = FeatureProto.scalaDescriptor.messages(6)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = org.tensorflow.example.feature.FeatureLists.FeatureListEntry
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.org.tensorflow.example.feature.FeatureLists.FeatureListEntry
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.tensorflow.example.feature.FeatureLists(
    featureList = _root_.scala.collection.immutable.Map.empty
  )
  @SerialVersionUID(0L)
  final case class FeatureListEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.scala.Option[org.tensorflow.example.feature.FeatureList] = _root_.scala.None,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[FeatureListEntry] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        if (value.isDefined) {
          val __value = value.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          val __m = __v
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        unknownFields.writeTo(_output__)
      }
      def withKey(__v: _root_.scala.Predef.String): FeatureListEntry = copy(key = __v)
      def getValue: org.tensorflow.example.feature.FeatureList = value.getOrElse(org.tensorflow.example.feature.FeatureList.defaultInstance)
      def clearValue: FeatureListEntry = copy(value = _root_.scala.None)
      def withValue(__v: org.tensorflow.example.feature.FeatureList): FeatureListEntry = copy(value = Option(__v))
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = org.tensorflow.example.feature.FeatureLists.FeatureListEntry
      // @@protoc_insertion_point(GeneratedMessage[tensorflow.FeatureLists.FeatureListEntry])
  }
  
  object FeatureListEntry extends scalapb.GeneratedMessageCompanion[org.tensorflow.example.feature.FeatureLists.FeatureListEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.example.feature.FeatureLists.FeatureListEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.example.feature.FeatureLists.FeatureListEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.scala.Option[org.tensorflow.example.feature.FeatureList] = _root_.scala.None
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = Option(__value.fold(_root_.scalapb.LiteParser.readMessage[org.tensorflow.example.feature.FeatureList](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      org.tensorflow.example.feature.FeatureLists.FeatureListEntry(
          key = __key,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.example.feature.FeatureLists.FeatureListEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        org.tensorflow.example.feature.FeatureLists.FeatureListEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[org.tensorflow.example.feature.FeatureList]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.tensorflow.example.feature.FeatureLists.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.tensorflow.example.feature.FeatureLists.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = org.tensorflow.example.feature.FeatureList
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = org.tensorflow.example.feature.FeatureLists.FeatureListEntry(
      key = "",
      value = _root_.scala.None
    )
    implicit class FeatureListEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.example.feature.FeatureLists.FeatureListEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.example.feature.FeatureLists.FeatureListEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.example.feature.FeatureList] = field(_.getValue)((c_, f_) => c_.copy(value = Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[org.tensorflow.example.feature.FeatureList]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[org.tensorflow.example.feature.FeatureLists.FeatureListEntry, (_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList)] =
      _root_.scalapb.TypeMapper[org.tensorflow.example.feature.FeatureLists.FeatureListEntry, (_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList)](__m => (__m.key, __m.getValue))(__p => org.tensorflow.example.feature.FeatureLists.FeatureListEntry(__p._1, Some(__p._2)))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.scala.Option[org.tensorflow.example.feature.FeatureList]
    ): _root_.org.tensorflow.example.feature.FeatureLists.FeatureListEntry = _root_.org.tensorflow.example.feature.FeatureLists.FeatureListEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.FeatureLists.FeatureListEntry])
  }
  
  implicit class FeatureListsLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.example.feature.FeatureLists]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.example.feature.FeatureLists](_l) {
    def featureList: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList]] = field(_.featureList)((c_, f_) => c_.copy(featureList = f_))
  }
  final val FEATURE_LIST_FIELD_NUMBER = 1
  @transient
  private[feature] val _typemapper_featureList: _root_.scalapb.TypeMapper[org.tensorflow.example.feature.FeatureLists.FeatureListEntry, (_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList)] = implicitly[_root_.scalapb.TypeMapper[org.tensorflow.example.feature.FeatureLists.FeatureListEntry, (_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList)]]
  def of(
    featureList: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.tensorflow.example.feature.FeatureList]
  ): _root_.org.tensorflow.example.feature.FeatureLists = _root_.org.tensorflow.example.feature.FeatureLists(
    featureList
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.FeatureLists])
}
