// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.tensor_shape

/** Dimensions of a tensor.
  *
  * @param dim
  *   Dimensions of the tensor, such as {"input", 30}, {"output", 40}
  *   for a 30 x 40 2D tensor.  If an entry has size -1, this
  *   corresponds to a dimension of unknown size. The names are
  *   optional.
  *  
  *   The order of entries in "dim" matters: It indicates the layout of the
  *   values in the tensor in-memory representation.
  *  
  *   The first entry in "dim" is the outermost dimension used to layout the
  *   values, the last entry is the innermost dimension.  This matches the
  *   in-memory layout of RowMajor Eigen tensors.
  *  
  *   If "dim.size()" &gt; 0, "unknown_rank" must be false.
  * @param unknownRank
  *   If true, the number of dimensions in the shape is unknown.
  *  
  *   If true, "dim.size()" must be 0.
  */
@SerialVersionUID(0L)
final case class TensorShapeProto(
    dim: _root_.scala.Seq[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim] = _root_.scala.Seq.empty,
    unknownRank: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[TensorShapeProto] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      dim.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = unknownRank
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      dim.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = unknownRank
        if (__v != false) {
          _output__.writeBool(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def clearDim = copy(dim = _root_.scala.Seq.empty)
    def addDim(__vs: org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim*): TensorShapeProto = addAllDim(__vs)
    def addAllDim(__vs: Iterable[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim]): TensorShapeProto = copy(dim = dim ++ __vs)
    def withDim(__v: _root_.scala.Seq[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim]): TensorShapeProto = copy(dim = __v)
    def withUnknownRank(__v: _root_.scala.Boolean): TensorShapeProto = copy(unknownRank = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 2 => dim
        case 3 => {
          val __t = unknownRank
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 2 => _root_.scalapb.descriptors.PRepeated(dim.iterator.map(_.toPMessage).toVector)
        case 3 => _root_.scalapb.descriptors.PBoolean(unknownRank)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = org.tensorflow.framework.tensor_shape.TensorShapeProto
    // @@protoc_insertion_point(GeneratedMessage[tensorflow.TensorShapeProto])
}

object TensorShapeProto extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.tensor_shape.TensorShapeProto] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.tensor_shape.TensorShapeProto] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.tensor_shape.TensorShapeProto = {
    val __dim: _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim] = new _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim]
    var __unknownRank: _root_.scala.Boolean = false
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 18 =>
          __dim += _root_.scalapb.LiteParser.readMessage[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim](_input__)
        case 24 =>
          __unknownRank = _input__.readBool()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.tensorflow.framework.tensor_shape.TensorShapeProto(
        dim = __dim.result(),
        unknownRank = __unknownRank,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.tensor_shape.TensorShapeProto] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.tensorflow.framework.tensor_shape.TensorShapeProto(
        dim = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim]]).getOrElse(_root_.scala.Seq.empty),
        unknownRank = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TensorShapeProtoCompanion.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TensorShapeProtoCompanion.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.tensorflow.framework.tensor_shape.TensorShapeProto(
    dim = _root_.scala.Seq.empty,
    unknownRank = false
  )
  /** One dimension of the tensor.
    *
    * @param size
    *   Size of the tensor in that dimension.
    *   This value must be &gt;= -1, but values of -1 are reserved for "unknown"
    *   shapes (values of -1 mean "unknown" dimension).  Certain wrappers
    *   that work with TensorShapeProto may fail at runtime when deserializing
    *   a TensorShapeProto containing a dim value of -1.
    * @param name
    *   Optional name of the tensor dimension.
    */
  @SerialVersionUID(0L)
  final case class Dim(
      size: _root_.scala.Long = 0L,
      name: _root_.scala.Predef.String = "",
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Dim] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = size
          if (__value != 0L) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
          }
        };
        
        {
          val __value = name
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = size
          if (__v != 0L) {
            _output__.writeInt64(1, __v)
          }
        };
        {
          val __v = name
          if (!__v.isEmpty) {
            _output__.writeString(2, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def withSize(__v: _root_.scala.Long): Dim = copy(size = __v)
      def withName(__v: _root_.scala.Predef.String): Dim = copy(name = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = size
            if (__t != 0L) __t else null
          }
          case 2 => {
            val __t = name
            if (__t != "") __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PLong(size)
          case 2 => _root_.scalapb.descriptors.PString(name)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim
      // @@protoc_insertion_point(GeneratedMessage[tensorflow.TensorShapeProto.Dim])
  }
  
  object Dim extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim = {
      var __size: _root_.scala.Long = 0L
      var __name: _root_.scala.Predef.String = ""
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __size = _input__.readInt64()
          case 18 =>
            __name = _input__.readStringRequireUtf8()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim(
          size = __size,
          name = __name,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim(
          size = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
          name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.tensorflow.framework.tensor_shape.TensorShapeProto.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.tensorflow.framework.tensor_shape.TensorShapeProto.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim(
      size = 0L,
      name = ""
    )
    implicit class DimLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim](_l) {
      def size: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.size)((c_, f_) => c_.copy(size = f_))
      def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    }
    final val SIZE_FIELD_NUMBER = 1
    final val NAME_FIELD_NUMBER = 2
    def of(
      size: _root_.scala.Long,
      name: _root_.scala.Predef.String
    ): _root_.org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim = _root_.org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim(
      size,
      name
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.TensorShapeProto.Dim])
  }
  
  implicit class TensorShapeProtoLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.tensor_shape.TensorShapeProto]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.tensor_shape.TensorShapeProto](_l) {
    def dim: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim]] = field(_.dim)((c_, f_) => c_.copy(dim = f_))
    def unknownRank: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.unknownRank)((c_, f_) => c_.copy(unknownRank = f_))
  }
  final val DIM_FIELD_NUMBER = 2
  final val UNKNOWN_RANK_FIELD_NUMBER = 3
  def of(
    dim: _root_.scala.Seq[org.tensorflow.framework.tensor_shape.TensorShapeProto.Dim],
    unknownRank: _root_.scala.Boolean
  ): _root_.org.tensorflow.framework.tensor_shape.TensorShapeProto = _root_.org.tensorflow.framework.tensor_shape.TensorShapeProto(
    dim,
    unknownRank
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.TensorShapeProto])
}
