// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.resource_handle

import com.google.protobuf.descriptor.FileDescriptorProto

object ResourceHandleProtoCompanion extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      org.tensorflow.framework.resource_handle.ResourceHandleProto
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChVyZXNvdXJjZV9oYW5kbGUucHJvdG8SCnRlbnNvcmZsb3ci8AEKE1Jlc291cmNlSGFuZGxlUHJvdG8SIwoGZGV2aWNlGAEgA
  SgJQgviPwgSBmRldmljZVIGZGV2aWNlEiwKCWNvbnRhaW5lchgCIAEoCUIO4j8LEgljb250YWluZXJSCWNvbnRhaW5lchIdCgRuY
  W1lGAMgASgJQgniPwYSBG5hbWVSBG5hbWUSKwoJaGFzaF9jb2RlGAQgASgEQg7iPwsSCV9oYXNoQ29kZVIIaGFzaENvZGUSOgoPb
  WF5YmVfdHlwZV9uYW1lGAUgASgJQhLiPw8SDW1heWJlVHlwZU5hbWVSDW1heWJlVHlwZU5hbWVCbgoYb3JnLnRlbnNvcmZsb3cuZ
  nJhbWV3b3JrQg5SZXNvdXJjZUhhbmRsZVABWj1naXRodWIuY29tL3RlbnNvcmZsb3cvdGVuc29yZmxvdy90ZW5zb3JmbG93L2dvL
  2NvcmUvZnJhbWV3b3Jr+AEBYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}