// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.op_def

/** Defines an operation. A NodeDef in a GraphDef specifies an Op by
  * using the "op" field which should match the name of a OpDef.
  * LINT.IfChange
  *
  * @param name
  *   Op names starting with an underscore are reserved for internal use.
  *   Names should be CamelCase and match the regexp "[A-Z][a-zA-Z0-9_]*".
  * @param inputArg
  *   Description of the input(s).
  * @param outputArg
  *   Description of the output(s).
  * @param deprecation
  *   Optional deprecation based on GraphDef versions.
  * @param summary
  *   One-line human-readable description of what the Op does.
  * @param description
  *   Additional, longer human-readable description of what the Op does.
  * @param isCommutative
  *   True if the operation is commutative ("op(a,b) == op(b,a)" for all inputs)
  * @param isAggregate
  *   If is_aggregate is true, then this operation accepts N &gt;= 2
  *   inputs and produces 1 output all of the same type.  Should be
  *   associative and commutative, and produce output with the same
  *   shape as the input.  The optimizer may replace an aggregate op
  *   taking input from multiple devices with a tree of aggregate ops
  *   that aggregate locally within each device (and possibly within
  *   groups of nearby devices) before communicating.
  *   TODO(josh11b): Implement that optimization.
  *   for things like add
  * @param isStateful
  *   Ops are marked as stateful if their behavior depends on some state beyond
  *   their input tensors (e.g. variable reading op) or if they have
  *   a side-effect (e.g. printing or asserting ops). Equivalently, stateless ops
  *   must always produce the same output for the same input and have
  *   no side-effects.
  *  
  *   By default Ops may be moved between devices.  Stateful ops should
  *   either not be moved, or should only be moved if that state can also
  *   be moved (e.g. via some sort of save / restore).
  *   Stateful ops are guaranteed to never be optimized away by Common
  *   Subexpression Elimination (CSE).
  *   for things like variables, queue
  * @param allowsUninitializedInput
  *   By default, all inputs to an Op must be initialized Tensors.  Ops
  *   that may initialize tensors for the first time should set this
  *   field to true, to allow the Op to take an uninitialized Tensor as
  *   input.
  *   for Assign, etc.
  */
@SerialVersionUID(0L)
final case class OpDef(
    name: _root_.scala.Predef.String = "",
    inputArg: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef] = _root_.scala.Seq.empty,
    outputArg: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef] = _root_.scala.Seq.empty,
    attr: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.AttrDef] = _root_.scala.Seq.empty,
    deprecation: _root_.scala.Option[org.tensorflow.framework.op_def.OpDeprecation] = _root_.scala.None,
    summary: _root_.scala.Predef.String = "",
    description: _root_.scala.Predef.String = "",
    isCommutative: _root_.scala.Boolean = false,
    isAggregate: _root_.scala.Boolean = false,
    isStateful: _root_.scala.Boolean = false,
    allowsUninitializedInput: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[OpDef] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      inputArg.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      outputArg.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      attr.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      if (deprecation.isDefined) {
        val __value = deprecation.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = summary
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      
      {
        val __value = description
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = isCommutative
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(18, __value)
        }
      };
      
      {
        val __value = isAggregate
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(16, __value)
        }
      };
      
      {
        val __value = isStateful
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(17, __value)
        }
      };
      
      {
        val __value = allowsUninitializedInput
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(19, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      inputArg.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      outputArg.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      attr.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = summary
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = description
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      deprecation.foreach { __v =>
        val __m = __v
        _output__.writeTag(8, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = isAggregate
        if (__v != false) {
          _output__.writeBool(16, __v)
        }
      };
      {
        val __v = isStateful
        if (__v != false) {
          _output__.writeBool(17, __v)
        }
      };
      {
        val __v = isCommutative
        if (__v != false) {
          _output__.writeBool(18, __v)
        }
      };
      {
        val __v = allowsUninitializedInput
        if (__v != false) {
          _output__.writeBool(19, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withName(__v: _root_.scala.Predef.String): OpDef = copy(name = __v)
    def clearInputArg = copy(inputArg = _root_.scala.Seq.empty)
    def addInputArg(__vs: org.tensorflow.framework.op_def.OpDef.ArgDef*): OpDef = addAllInputArg(__vs)
    def addAllInputArg(__vs: Iterable[org.tensorflow.framework.op_def.OpDef.ArgDef]): OpDef = copy(inputArg = inputArg ++ __vs)
    def withInputArg(__v: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef]): OpDef = copy(inputArg = __v)
    def clearOutputArg = copy(outputArg = _root_.scala.Seq.empty)
    def addOutputArg(__vs: org.tensorflow.framework.op_def.OpDef.ArgDef*): OpDef = addAllOutputArg(__vs)
    def addAllOutputArg(__vs: Iterable[org.tensorflow.framework.op_def.OpDef.ArgDef]): OpDef = copy(outputArg = outputArg ++ __vs)
    def withOutputArg(__v: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef]): OpDef = copy(outputArg = __v)
    def clearAttr = copy(attr = _root_.scala.Seq.empty)
    def addAttr(__vs: org.tensorflow.framework.op_def.OpDef.AttrDef*): OpDef = addAllAttr(__vs)
    def addAllAttr(__vs: Iterable[org.tensorflow.framework.op_def.OpDef.AttrDef]): OpDef = copy(attr = attr ++ __vs)
    def withAttr(__v: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.AttrDef]): OpDef = copy(attr = __v)
    def getDeprecation: org.tensorflow.framework.op_def.OpDeprecation = deprecation.getOrElse(org.tensorflow.framework.op_def.OpDeprecation.defaultInstance)
    def clearDeprecation: OpDef = copy(deprecation = _root_.scala.None)
    def withDeprecation(__v: org.tensorflow.framework.op_def.OpDeprecation): OpDef = copy(deprecation = Option(__v))
    def withSummary(__v: _root_.scala.Predef.String): OpDef = copy(summary = __v)
    def withDescription(__v: _root_.scala.Predef.String): OpDef = copy(description = __v)
    def withIsCommutative(__v: _root_.scala.Boolean): OpDef = copy(isCommutative = __v)
    def withIsAggregate(__v: _root_.scala.Boolean): OpDef = copy(isAggregate = __v)
    def withIsStateful(__v: _root_.scala.Boolean): OpDef = copy(isStateful = __v)
    def withAllowsUninitializedInput(__v: _root_.scala.Boolean): OpDef = copy(allowsUninitializedInput = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 2 => inputArg
        case 3 => outputArg
        case 4 => attr
        case 8 => deprecation.orNull
        case 5 => {
          val __t = summary
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = description
          if (__t != "") __t else null
        }
        case 18 => {
          val __t = isCommutative
          if (__t != false) __t else null
        }
        case 16 => {
          val __t = isAggregate
          if (__t != false) __t else null
        }
        case 17 => {
          val __t = isStateful
          if (__t != false) __t else null
        }
        case 19 => {
          val __t = allowsUninitializedInput
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 2 => _root_.scalapb.descriptors.PRepeated(inputArg.iterator.map(_.toPMessage).toVector)
        case 3 => _root_.scalapb.descriptors.PRepeated(outputArg.iterator.map(_.toPMessage).toVector)
        case 4 => _root_.scalapb.descriptors.PRepeated(attr.iterator.map(_.toPMessage).toVector)
        case 8 => deprecation.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 5 => _root_.scalapb.descriptors.PString(summary)
        case 6 => _root_.scalapb.descriptors.PString(description)
        case 18 => _root_.scalapb.descriptors.PBoolean(isCommutative)
        case 16 => _root_.scalapb.descriptors.PBoolean(isAggregate)
        case 17 => _root_.scalapb.descriptors.PBoolean(isStateful)
        case 19 => _root_.scalapb.descriptors.PBoolean(allowsUninitializedInput)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = org.tensorflow.framework.op_def.OpDef
    // @@protoc_insertion_point(GeneratedMessage[tensorflow.OpDef])
}

object OpDef extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.op_def.OpDef] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.op_def.OpDef] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.op_def.OpDef = {
    var __name: _root_.scala.Predef.String = ""
    val __inputArg: _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.op_def.OpDef.ArgDef] = new _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.op_def.OpDef.ArgDef]
    val __outputArg: _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.op_def.OpDef.ArgDef] = new _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.op_def.OpDef.ArgDef]
    val __attr: _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.op_def.OpDef.AttrDef] = new _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.op_def.OpDef.AttrDef]
    var __deprecation: _root_.scala.Option[org.tensorflow.framework.op_def.OpDeprecation] = _root_.scala.None
    var __summary: _root_.scala.Predef.String = ""
    var __description: _root_.scala.Predef.String = ""
    var __isCommutative: _root_.scala.Boolean = false
    var __isAggregate: _root_.scala.Boolean = false
    var __isStateful: _root_.scala.Boolean = false
    var __allowsUninitializedInput: _root_.scala.Boolean = false
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __name = _input__.readStringRequireUtf8()
        case 18 =>
          __inputArg += _root_.scalapb.LiteParser.readMessage[org.tensorflow.framework.op_def.OpDef.ArgDef](_input__)
        case 26 =>
          __outputArg += _root_.scalapb.LiteParser.readMessage[org.tensorflow.framework.op_def.OpDef.ArgDef](_input__)
        case 34 =>
          __attr += _root_.scalapb.LiteParser.readMessage[org.tensorflow.framework.op_def.OpDef.AttrDef](_input__)
        case 66 =>
          __deprecation = Option(__deprecation.fold(_root_.scalapb.LiteParser.readMessage[org.tensorflow.framework.op_def.OpDeprecation](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 42 =>
          __summary = _input__.readStringRequireUtf8()
        case 50 =>
          __description = _input__.readStringRequireUtf8()
        case 144 =>
          __isCommutative = _input__.readBool()
        case 128 =>
          __isAggregate = _input__.readBool()
        case 136 =>
          __isStateful = _input__.readBool()
        case 152 =>
          __allowsUninitializedInput = _input__.readBool()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.tensorflow.framework.op_def.OpDef(
        name = __name,
        inputArg = __inputArg.result(),
        outputArg = __outputArg.result(),
        attr = __attr.result(),
        deprecation = __deprecation,
        summary = __summary,
        description = __description,
        isCommutative = __isCommutative,
        isAggregate = __isAggregate,
        isStateful = __isStateful,
        allowsUninitializedInput = __allowsUninitializedInput,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.op_def.OpDef] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.tensorflow.framework.op_def.OpDef(
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        inputArg = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef]]).getOrElse(_root_.scala.Seq.empty),
        outputArg = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef]]).getOrElse(_root_.scala.Seq.empty),
        attr = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.AttrDef]]).getOrElse(_root_.scala.Seq.empty),
        deprecation = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).flatMap(_.as[_root_.scala.Option[org.tensorflow.framework.op_def.OpDeprecation]]),
        summary = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        isCommutative = __fieldsMap.get(scalaDescriptor.findFieldByNumber(18).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        isAggregate = __fieldsMap.get(scalaDescriptor.findFieldByNumber(16).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        isStateful = __fieldsMap.get(scalaDescriptor.findFieldByNumber(17).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        allowsUninitializedInput = __fieldsMap.get(scalaDescriptor.findFieldByNumber(19).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = OpDefProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = OpDefProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = org.tensorflow.framework.op_def.OpDef.ArgDef
      case 3 => __out = org.tensorflow.framework.op_def.OpDef.ArgDef
      case 4 => __out = org.tensorflow.framework.op_def.OpDef.AttrDef
      case 8 => __out = org.tensorflow.framework.op_def.OpDeprecation
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.org.tensorflow.framework.op_def.OpDef.ArgDef,
      _root_.org.tensorflow.framework.op_def.OpDef.AttrDef
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.tensorflow.framework.op_def.OpDef(
    name = "",
    inputArg = _root_.scala.Seq.empty,
    outputArg = _root_.scala.Seq.empty,
    attr = _root_.scala.Seq.empty,
    deprecation = _root_.scala.None,
    summary = "",
    description = "",
    isCommutative = false,
    isAggregate = false,
    isStateful = false,
    allowsUninitializedInput = false
  )
  /** For describing inputs and outputs.
    *
    * @param name
    *   Name for the input/output.  Should match the regexp "[a-z][a-z0-9_]*".
    * @param description
    *   Human readable description.
    * @param type
    *   Describes the type of one or more tensors that are accepted/produced
    *   by this input/output arg.  The only legal combinations are:
    *   * For a single tensor: either the "type" field is set or the
    *     "type_attr" field is set to the name of an attr with type "type".
    *   * For a sequence of tensors with the same type: the "number_attr"
    *     field will be set to the name of an attr with type "int", and
    *     either the "type" or "type_attr" field will be set as for
    *     single tensors.
    *   * For a sequence of tensors, the "type_list_attr" field will be set
    *     to the name of an attr with type "list(type)".
    * @param typeAttr
    *   if specified, attr must have type "type"
    * @param numberAttr
    *   if specified, attr must have type "int"
    * @param typeListAttr
    *   If specified, attr must have type "list(type)", and none of
    *   type, type_attr, and number_attr may be specified.
    * @param isRef
    *   For inputs: if true, the inputs are required to be refs.
    *     By default, inputs can be either refs or non-refs.
    *   For outputs: if true, outputs are refs, otherwise they are not.
    */
  @SerialVersionUID(0L)
  final case class ArgDef(
      name: _root_.scala.Predef.String = "",
      description: _root_.scala.Predef.String = "",
      `type`: org.tensorflow.framework.types.DataType = org.tensorflow.framework.types.DataType.DT_INVALID,
      typeAttr: _root_.scala.Predef.String = "",
      numberAttr: _root_.scala.Predef.String = "",
      typeListAttr: _root_.scala.Predef.String = "",
      isRef: _root_.scala.Boolean = false,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ArgDef] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = name
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = description
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
          }
        };
        
        {
          val __value = `type`.value
          if (__value != 0) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(3, __value)
          }
        };
        
        {
          val __value = typeAttr
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
          }
        };
        
        {
          val __value = numberAttr
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
          }
        };
        
        {
          val __value = typeListAttr
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
          }
        };
        
        {
          val __value = isRef
          if (__value != false) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(16, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = name
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = description
          if (!__v.isEmpty) {
            _output__.writeString(2, __v)
          }
        };
        {
          val __v = `type`.value
          if (__v != 0) {
            _output__.writeEnum(3, __v)
          }
        };
        {
          val __v = typeAttr
          if (!__v.isEmpty) {
            _output__.writeString(4, __v)
          }
        };
        {
          val __v = numberAttr
          if (!__v.isEmpty) {
            _output__.writeString(5, __v)
          }
        };
        {
          val __v = typeListAttr
          if (!__v.isEmpty) {
            _output__.writeString(6, __v)
          }
        };
        {
          val __v = isRef
          if (__v != false) {
            _output__.writeBool(16, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def withName(__v: _root_.scala.Predef.String): ArgDef = copy(name = __v)
      def withDescription(__v: _root_.scala.Predef.String): ArgDef = copy(description = __v)
      def withType(__v: org.tensorflow.framework.types.DataType): ArgDef = copy(`type` = __v)
      def withTypeAttr(__v: _root_.scala.Predef.String): ArgDef = copy(typeAttr = __v)
      def withNumberAttr(__v: _root_.scala.Predef.String): ArgDef = copy(numberAttr = __v)
      def withTypeListAttr(__v: _root_.scala.Predef.String): ArgDef = copy(typeListAttr = __v)
      def withIsRef(__v: _root_.scala.Boolean): ArgDef = copy(isRef = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = name
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = description
            if (__t != "") __t else null
          }
          case 3 => {
            val __t = `type`.javaValueDescriptor
            if (__t.getNumber() != 0) __t else null
          }
          case 4 => {
            val __t = typeAttr
            if (__t != "") __t else null
          }
          case 5 => {
            val __t = numberAttr
            if (__t != "") __t else null
          }
          case 6 => {
            val __t = typeListAttr
            if (__t != "") __t else null
          }
          case 16 => {
            val __t = isRef
            if (__t != false) __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(name)
          case 2 => _root_.scalapb.descriptors.PString(description)
          case 3 => _root_.scalapb.descriptors.PEnum(`type`.scalaValueDescriptor)
          case 4 => _root_.scalapb.descriptors.PString(typeAttr)
          case 5 => _root_.scalapb.descriptors.PString(numberAttr)
          case 6 => _root_.scalapb.descriptors.PString(typeListAttr)
          case 16 => _root_.scalapb.descriptors.PBoolean(isRef)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = org.tensorflow.framework.op_def.OpDef.ArgDef
      // @@protoc_insertion_point(GeneratedMessage[tensorflow.OpDef.ArgDef])
  }
  
  object ArgDef extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.op_def.OpDef.ArgDef] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.op_def.OpDef.ArgDef] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.op_def.OpDef.ArgDef = {
      var __name: _root_.scala.Predef.String = ""
      var __description: _root_.scala.Predef.String = ""
      var __type: org.tensorflow.framework.types.DataType = org.tensorflow.framework.types.DataType.DT_INVALID
      var __typeAttr: _root_.scala.Predef.String = ""
      var __numberAttr: _root_.scala.Predef.String = ""
      var __typeListAttr: _root_.scala.Predef.String = ""
      var __isRef: _root_.scala.Boolean = false
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __name = _input__.readStringRequireUtf8()
          case 18 =>
            __description = _input__.readStringRequireUtf8()
          case 24 =>
            __type = org.tensorflow.framework.types.DataType.fromValue(_input__.readEnum())
          case 34 =>
            __typeAttr = _input__.readStringRequireUtf8()
          case 42 =>
            __numberAttr = _input__.readStringRequireUtf8()
          case 50 =>
            __typeListAttr = _input__.readStringRequireUtf8()
          case 128 =>
            __isRef = _input__.readBool()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      org.tensorflow.framework.op_def.OpDef.ArgDef(
          name = __name,
          description = __description,
          `type` = __type,
          typeAttr = __typeAttr,
          numberAttr = __numberAttr,
          typeListAttr = __typeListAttr,
          isRef = __isRef,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.op_def.OpDef.ArgDef] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        org.tensorflow.framework.op_def.OpDef.ArgDef(
          name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          `type` = org.tensorflow.framework.types.DataType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(org.tensorflow.framework.types.DataType.DT_INVALID.scalaValueDescriptor).number),
          typeAttr = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          numberAttr = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          typeListAttr = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          isRef = __fieldsMap.get(scalaDescriptor.findFieldByNumber(16).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.tensorflow.framework.op_def.OpDef.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.tensorflow.framework.op_def.OpDef.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 3 => org.tensorflow.framework.types.DataType
      }
    }
    lazy val defaultInstance = org.tensorflow.framework.op_def.OpDef.ArgDef(
      name = "",
      description = "",
      `type` = org.tensorflow.framework.types.DataType.DT_INVALID,
      typeAttr = "",
      numberAttr = "",
      typeListAttr = "",
      isRef = false
    )
    implicit class ArgDefLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.op_def.OpDef.ArgDef]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.op_def.OpDef.ArgDef](_l) {
      def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
      def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
      def `type`: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.types.DataType] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
      def typeAttr: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.typeAttr)((c_, f_) => c_.copy(typeAttr = f_))
      def numberAttr: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.numberAttr)((c_, f_) => c_.copy(numberAttr = f_))
      def typeListAttr: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.typeListAttr)((c_, f_) => c_.copy(typeListAttr = f_))
      def isRef: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isRef)((c_, f_) => c_.copy(isRef = f_))
    }
    final val NAME_FIELD_NUMBER = 1
    final val DESCRIPTION_FIELD_NUMBER = 2
    final val TYPE_FIELD_NUMBER = 3
    final val TYPE_ATTR_FIELD_NUMBER = 4
    final val NUMBER_ATTR_FIELD_NUMBER = 5
    final val TYPE_LIST_ATTR_FIELD_NUMBER = 6
    final val IS_REF_FIELD_NUMBER = 16
    def of(
      name: _root_.scala.Predef.String,
      description: _root_.scala.Predef.String,
      `type`: org.tensorflow.framework.types.DataType,
      typeAttr: _root_.scala.Predef.String,
      numberAttr: _root_.scala.Predef.String,
      typeListAttr: _root_.scala.Predef.String,
      isRef: _root_.scala.Boolean
    ): _root_.org.tensorflow.framework.op_def.OpDef.ArgDef = _root_.org.tensorflow.framework.op_def.OpDef.ArgDef(
      name,
      description,
      `type`,
      typeAttr,
      numberAttr,
      typeListAttr,
      isRef
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.OpDef.ArgDef])
  }
  
  /** Description of the graph-construction-time configuration of this
    * Op.  That is to say, this describes the attr fields that will
    * be specified in the NodeDef.
    *
    * @param name
    *   A descriptive name for the argument.  May be used, e.g. by the
    *   Python client, as a keyword argument name, and so should match
    *   the regexp "[a-z][a-z0-9_]+".
    * @param type
    *   One of the type names from attr_value.proto ("string", "list(string)",
    *   "int", etc.).
    * @param defaultValue
    *   A reasonable default for this attribute if the user does not supply
    *   a value.  If not specified, the user must supply a value.
    * @param description
    *   Human-readable description.
    * @param hasMinimum
    *   For type == "int", this is a minimum value.  For "list(___)"
    *   types, this is the minimum length.
    * @param allowedValues
    *   The set of allowed values.  Has type that is the "list" version
    *   of the "type" field above (uses the "list" field of AttrValue).
    *   If type == "type" or "list(type)" above, then the "type" field
    *   of "allowed_values.list" has the set of allowed DataTypes.
    *   If type == "string" or "list(string)", then the "s" field of
    *   "allowed_values.list" has the set of allowed strings.
    */
  @SerialVersionUID(0L)
  final case class AttrDef(
      name: _root_.scala.Predef.String = "",
      `type`: _root_.scala.Predef.String = "",
      defaultValue: _root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue] = _root_.scala.None,
      description: _root_.scala.Predef.String = "",
      hasMinimum: _root_.scala.Boolean = false,
      minimum: _root_.scala.Long = 0L,
      allowedValues: _root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue] = _root_.scala.None,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[AttrDef] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = name
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = `type`
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
          }
        };
        if (defaultValue.isDefined) {
          val __value = defaultValue.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        
        {
          val __value = description
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
          }
        };
        
        {
          val __value = hasMinimum
          if (__value != false) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(5, __value)
          }
        };
        
        {
          val __value = minimum
          if (__value != 0L) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(6, __value)
          }
        };
        if (allowedValues.isDefined) {
          val __value = allowedValues.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = name
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = `type`
          if (!__v.isEmpty) {
            _output__.writeString(2, __v)
          }
        };
        defaultValue.foreach { __v =>
          val __m = __v
          _output__.writeTag(3, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        {
          val __v = description
          if (!__v.isEmpty) {
            _output__.writeString(4, __v)
          }
        };
        {
          val __v = hasMinimum
          if (__v != false) {
            _output__.writeBool(5, __v)
          }
        };
        {
          val __v = minimum
          if (__v != 0L) {
            _output__.writeInt64(6, __v)
          }
        };
        allowedValues.foreach { __v =>
          val __m = __v
          _output__.writeTag(7, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        unknownFields.writeTo(_output__)
      }
      def withName(__v: _root_.scala.Predef.String): AttrDef = copy(name = __v)
      def withType(__v: _root_.scala.Predef.String): AttrDef = copy(`type` = __v)
      def getDefaultValue: org.tensorflow.framework.attr_value.AttrValue = defaultValue.getOrElse(org.tensorflow.framework.attr_value.AttrValue.defaultInstance)
      def clearDefaultValue: AttrDef = copy(defaultValue = _root_.scala.None)
      def withDefaultValue(__v: org.tensorflow.framework.attr_value.AttrValue): AttrDef = copy(defaultValue = Option(__v))
      def withDescription(__v: _root_.scala.Predef.String): AttrDef = copy(description = __v)
      def withHasMinimum(__v: _root_.scala.Boolean): AttrDef = copy(hasMinimum = __v)
      def withMinimum(__v: _root_.scala.Long): AttrDef = copy(minimum = __v)
      def getAllowedValues: org.tensorflow.framework.attr_value.AttrValue = allowedValues.getOrElse(org.tensorflow.framework.attr_value.AttrValue.defaultInstance)
      def clearAllowedValues: AttrDef = copy(allowedValues = _root_.scala.None)
      def withAllowedValues(__v: org.tensorflow.framework.attr_value.AttrValue): AttrDef = copy(allowedValues = Option(__v))
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = name
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = `type`
            if (__t != "") __t else null
          }
          case 3 => defaultValue.orNull
          case 4 => {
            val __t = description
            if (__t != "") __t else null
          }
          case 5 => {
            val __t = hasMinimum
            if (__t != false) __t else null
          }
          case 6 => {
            val __t = minimum
            if (__t != 0L) __t else null
          }
          case 7 => allowedValues.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(name)
          case 2 => _root_.scalapb.descriptors.PString(`type`)
          case 3 => defaultValue.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
          case 4 => _root_.scalapb.descriptors.PString(description)
          case 5 => _root_.scalapb.descriptors.PBoolean(hasMinimum)
          case 6 => _root_.scalapb.descriptors.PLong(minimum)
          case 7 => allowedValues.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = org.tensorflow.framework.op_def.OpDef.AttrDef
      // @@protoc_insertion_point(GeneratedMessage[tensorflow.OpDef.AttrDef])
  }
  
  object AttrDef extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.op_def.OpDef.AttrDef] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.op_def.OpDef.AttrDef] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.op_def.OpDef.AttrDef = {
      var __name: _root_.scala.Predef.String = ""
      var __type: _root_.scala.Predef.String = ""
      var __defaultValue: _root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue] = _root_.scala.None
      var __description: _root_.scala.Predef.String = ""
      var __hasMinimum: _root_.scala.Boolean = false
      var __minimum: _root_.scala.Long = 0L
      var __allowedValues: _root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue] = _root_.scala.None
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __name = _input__.readStringRequireUtf8()
          case 18 =>
            __type = _input__.readStringRequireUtf8()
          case 26 =>
            __defaultValue = Option(__defaultValue.fold(_root_.scalapb.LiteParser.readMessage[org.tensorflow.framework.attr_value.AttrValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case 34 =>
            __description = _input__.readStringRequireUtf8()
          case 40 =>
            __hasMinimum = _input__.readBool()
          case 48 =>
            __minimum = _input__.readInt64()
          case 58 =>
            __allowedValues = Option(__allowedValues.fold(_root_.scalapb.LiteParser.readMessage[org.tensorflow.framework.attr_value.AttrValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      org.tensorflow.framework.op_def.OpDef.AttrDef(
          name = __name,
          `type` = __type,
          defaultValue = __defaultValue,
          description = __description,
          hasMinimum = __hasMinimum,
          minimum = __minimum,
          allowedValues = __allowedValues,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.op_def.OpDef.AttrDef] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        org.tensorflow.framework.op_def.OpDef.AttrDef(
          name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          `type` = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          defaultValue = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue]]),
          description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          hasMinimum = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
          minimum = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
          allowedValues = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).flatMap(_.as[_root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.tensorflow.framework.op_def.OpDef.javaDescriptor.getNestedTypes().get(1)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.tensorflow.framework.op_def.OpDef.scalaDescriptor.nestedMessages(1)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 3 => __out = org.tensorflow.framework.attr_value.AttrValue
        case 7 => __out = org.tensorflow.framework.attr_value.AttrValue
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = org.tensorflow.framework.op_def.OpDef.AttrDef(
      name = "",
      `type` = "",
      defaultValue = _root_.scala.None,
      description = "",
      hasMinimum = false,
      minimum = 0L,
      allowedValues = _root_.scala.None
    )
    implicit class AttrDefLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.op_def.OpDef.AttrDef]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.op_def.OpDef.AttrDef](_l) {
      def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
      def `type`: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
      def defaultValue: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.attr_value.AttrValue] = field(_.getDefaultValue)((c_, f_) => c_.copy(defaultValue = Option(f_)))
      def optionalDefaultValue: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue]] = field(_.defaultValue)((c_, f_) => c_.copy(defaultValue = f_))
      def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
      def hasMinimum: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.hasMinimum)((c_, f_) => c_.copy(hasMinimum = f_))
      def minimum: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.minimum)((c_, f_) => c_.copy(minimum = f_))
      def allowedValues: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.attr_value.AttrValue] = field(_.getAllowedValues)((c_, f_) => c_.copy(allowedValues = Option(f_)))
      def optionalAllowedValues: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue]] = field(_.allowedValues)((c_, f_) => c_.copy(allowedValues = f_))
    }
    final val NAME_FIELD_NUMBER = 1
    final val TYPE_FIELD_NUMBER = 2
    final val DEFAULT_VALUE_FIELD_NUMBER = 3
    final val DESCRIPTION_FIELD_NUMBER = 4
    final val HAS_MINIMUM_FIELD_NUMBER = 5
    final val MINIMUM_FIELD_NUMBER = 6
    final val ALLOWED_VALUES_FIELD_NUMBER = 7
    def of(
      name: _root_.scala.Predef.String,
      `type`: _root_.scala.Predef.String,
      defaultValue: _root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue],
      description: _root_.scala.Predef.String,
      hasMinimum: _root_.scala.Boolean,
      minimum: _root_.scala.Long,
      allowedValues: _root_.scala.Option[org.tensorflow.framework.attr_value.AttrValue]
    ): _root_.org.tensorflow.framework.op_def.OpDef.AttrDef = _root_.org.tensorflow.framework.op_def.OpDef.AttrDef(
      name,
      `type`,
      defaultValue,
      description,
      hasMinimum,
      minimum,
      allowedValues
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.OpDef.AttrDef])
  }
  
  implicit class OpDefLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.op_def.OpDef]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.op_def.OpDef](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def inputArg: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef]] = field(_.inputArg)((c_, f_) => c_.copy(inputArg = f_))
    def outputArg: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef]] = field(_.outputArg)((c_, f_) => c_.copy(outputArg = f_))
    def attr: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.AttrDef]] = field(_.attr)((c_, f_) => c_.copy(attr = f_))
    def deprecation: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.op_def.OpDeprecation] = field(_.getDeprecation)((c_, f_) => c_.copy(deprecation = Option(f_)))
    def optionalDeprecation: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[org.tensorflow.framework.op_def.OpDeprecation]] = field(_.deprecation)((c_, f_) => c_.copy(deprecation = f_))
    def summary: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.summary)((c_, f_) => c_.copy(summary = f_))
    def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
    def isCommutative: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isCommutative)((c_, f_) => c_.copy(isCommutative = f_))
    def isAggregate: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isAggregate)((c_, f_) => c_.copy(isAggregate = f_))
    def isStateful: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isStateful)((c_, f_) => c_.copy(isStateful = f_))
    def allowsUninitializedInput: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.allowsUninitializedInput)((c_, f_) => c_.copy(allowsUninitializedInput = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val INPUT_ARG_FIELD_NUMBER = 2
  final val OUTPUT_ARG_FIELD_NUMBER = 3
  final val ATTR_FIELD_NUMBER = 4
  final val DEPRECATION_FIELD_NUMBER = 8
  final val SUMMARY_FIELD_NUMBER = 5
  final val DESCRIPTION_FIELD_NUMBER = 6
  final val IS_COMMUTATIVE_FIELD_NUMBER = 18
  final val IS_AGGREGATE_FIELD_NUMBER = 16
  final val IS_STATEFUL_FIELD_NUMBER = 17
  final val ALLOWS_UNINITIALIZED_INPUT_FIELD_NUMBER = 19
  def of(
    name: _root_.scala.Predef.String,
    inputArg: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef],
    outputArg: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.ArgDef],
    attr: _root_.scala.Seq[org.tensorflow.framework.op_def.OpDef.AttrDef],
    deprecation: _root_.scala.Option[org.tensorflow.framework.op_def.OpDeprecation],
    summary: _root_.scala.Predef.String,
    description: _root_.scala.Predef.String,
    isCommutative: _root_.scala.Boolean,
    isAggregate: _root_.scala.Boolean,
    isStateful: _root_.scala.Boolean,
    allowsUninitializedInput: _root_.scala.Boolean
  ): _root_.org.tensorflow.framework.op_def.OpDef = _root_.org.tensorflow.framework.op_def.OpDef(
    name,
    inputArg,
    outputArg,
    attr,
    deprecation,
    summary,
    description,
    isCommutative,
    isAggregate,
    isStateful,
    allowsUninitializedInput
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.OpDef])
}
