// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.error_codes

import com.google.protobuf.descriptor.FileDescriptorProto

object ErrorCodesProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChFlcnJvcl9jb2Rlcy5wcm90bxIQdGVuc29yZmxvdy5lcnJvciqEAwoEQ29kZRIGCgJPSxAAEg0KCUNBTkNFTExFRBABEgsKB
  1VOS05PV04QAhIUChBJTlZBTElEX0FSR1VNRU5UEAMSFQoRREVBRExJTkVfRVhDRUVERUQQBBINCglOT1RfRk9VTkQQBRISCg5BT
  FJFQURZX0VYSVNUUxAGEhUKEVBFUk1JU1NJT05fREVOSUVEEAcSEwoPVU5BVVRIRU5USUNBVEVEEBASFgoSUkVTT1VSQ0VfRVhIQ
  VVTVEVEEAgSFwoTRkFJTEVEX1BSRUNPTkRJVElPThAJEgsKB0FCT1JURUQQChIQCgxPVVRfT0ZfUkFOR0UQCxIRCg1VTklNUExFT
  UVOVEVEEAwSDAoISU5URVJOQUwQDRIPCgtVTkFWQUlMQUJMRRAOEg0KCURBVEFfTE9TUxAPEksKR0RPX05PVF9VU0VfUkVTRVJWR
  URfRk9SX0ZVVFVSRV9FWFBBTlNJT05fVVNFX0RFRkFVTFRfSU5fU1dJVENIX0lOU1RFQURfEBRCbwoYb3JnLnRlbnNvcmZsb3cuZ
  nJhbWV3b3JrQhBFcnJvckNvZGVzUHJvdG9zUAFaPGdpdGh1Yi5jb20vdGVuc29yZmxvdy90ZW5zb3JmbG93L3RlbnNvcmZsb3cvZ
  28vY29yZS9saWIvY29yZfgBAWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}