// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.example.example

import com.google.protobuf.descriptor.FileDescriptorProto

object ExampleProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    org.tensorflow.example.feature.FeatureProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      org.tensorflow.example.example.Example,
      org.tensorflow.example.example.SequenceExample
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg1leGFtcGxlLnByb3RvEgp0ZW5zb3JmbG93Gg1mZWF0dXJlLnByb3RvIkoKB0V4YW1wbGUSPwoIZmVhdHVyZXMYASABKAsyF
  C50ZW5zb3JmbG93LkZlYXR1cmVzQg3iPwoSCGZlYXR1cmVzUghmZWF0dXJlcyKhAQoPU2VxdWVuY2VFeGFtcGxlEjwKB2NvbnRle
  HQYASABKAsyFC50ZW5zb3JmbG93LkZlYXR1cmVzQgziPwkSB2NvbnRleHRSB2NvbnRleHQSUAoNZmVhdHVyZV9saXN0cxgCIAEoC
  zIYLnRlbnNvcmZsb3cuRmVhdHVyZUxpc3RzQhHiPw4SDGZlYXR1cmVMaXN0c1IMZmVhdHVyZUxpc3RzQmkKFm9yZy50ZW5zb3Jmb
  G93LmV4YW1wbGVCDUV4YW1wbGVQcm90b3NQAVo7Z2l0aHViLmNvbS90ZW5zb3JmbG93L3RlbnNvcmZsb3cvdGVuc29yZmxvdy9nb
  y9jb3JlL2V4YW1wbGX4AQFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom( scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      org.tensorflow.example.feature.FeatureProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}