// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.node_def

import com.google.protobuf.descriptor.FileDescriptorProto

object NodeDefProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    org.tensorflow.framework.attr_value.AttrValueProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      org.tensorflow.framework.node_def.NodeDef
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg5ub2RlX2RlZi5wcm90bxIKdGVuc29yZmxvdxoQYXR0cl92YWx1ZS5wcm90byKMBAoHTm9kZURlZhIdCgRuYW1lGAEgASgJQ
  gniPwYSBG5hbWVSBG5hbWUSFwoCb3AYAiABKAlCB+I/BBICb3BSAm9wEiAKBWlucHV0GAMgAygJQgriPwcSBWlucHV0UgVpbnB1d
  BIjCgZkZXZpY2UYBCABKAlCC+I/CBIGZGV2aWNlUgZkZXZpY2USPAoEYXR0chgFIAMoCzIdLnRlbnNvcmZsb3cuTm9kZURlZi5Bd
  HRyRW50cnlCCeI/BhIEYXR0clIEYXR0chJ9ChdleHBlcmltZW50YWxfZGVidWdfaW5mbxgGIAEoCzIpLnRlbnNvcmZsb3cuTm9kZ
  URlZi5FeHBlcmltZW50YWxEZWJ1Z0luZm9CGuI/FxIVZXhwZXJpbWVudGFsRGVidWdJbmZvUhVleHBlcmltZW50YWxEZWJ1Z0luZ
  m8aZAoJQXR0ckVudHJ5EhoKA2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRI3CgV2YWx1ZRgCIAEoCzIVLnRlbnNvcmZsb3cuQXR0c
  lZhbHVlQgriPwcSBXZhbHVlUgV2YWx1ZToCOAEaXwoVRXhwZXJpbWVudGFsRGVidWdJbmZvEkYKE29yaWdpbmFsX25vZGVfbmFtZ
  XMYASADKAlCFuI/ExIRb3JpZ2luYWxOb2RlTmFtZXNSEW9yaWdpbmFsTm9kZU5hbWVzQmkKGG9yZy50ZW5zb3JmbG93LmZyYW1ld
  29ya0IJTm9kZVByb3RvUAFaPWdpdGh1Yi5jb20vdGVuc29yZmxvdy90ZW5zb3JmbG93L3RlbnNvcmZsb3cvZ28vY29yZS9mcmFtZ
  Xdvcmv4AQFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      org.tensorflow.framework.attr_value.AttrValueProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}