// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.graph

import com.google.protobuf.descriptor.FileDescriptorProto

object GraphProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    org.tensorflow.framework.node_def.NodeDefProto,
    org.tensorflow.framework.function.FunctionProto,
    org.tensorflow.framework.versions.VersionsProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      org.tensorflow.framework.graph.GraphDef
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgtncmFwaC5wcm90bxIKdGVuc29yZmxvdxoObm9kZV9kZWYucHJvdG8aDmZ1bmN0aW9uLnByb3RvGg52ZXJzaW9ucy5wcm90b
  yLzAQoIR3JhcGhEZWYSMgoEbm9kZRgBIAMoCzITLnRlbnNvcmZsb3cuTm9kZURlZkIJ4j8GEgRub2RlUgRub2RlEkEKCHZlcnNpb
  25zGAQgASgLMhYudGVuc29yZmxvdy5WZXJzaW9uRGVmQg3iPwoSCHZlcnNpb25zUgh2ZXJzaW9ucxIoCgd2ZXJzaW9uGAMgASgFQ
  g4YAeI/CRIHdmVyc2lvblIHdmVyc2lvbhJGCgdsaWJyYXJ5GAIgASgLMh4udGVuc29yZmxvdy5GdW5jdGlvbkRlZkxpYnJhcnlCD
  OI/CRIHbGlicmFyeVIHbGlicmFyeUJrChhvcmcudGVuc29yZmxvdy5mcmFtZXdvcmtCC0dyYXBoUHJvdG9zUAFaPWdpdGh1Yi5jb
  20vdGVuc29yZmxvdy90ZW5zb3JmbG93L3RlbnNvcmZsb3cvZ28vY29yZS9mcmFtZXdvcmv4AQFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      org.tensorflow.framework.node_def.NodeDefProto.javaDescriptor,
      org.tensorflow.framework.function.FunctionProto.javaDescriptor,
      org.tensorflow.framework.versions.VersionsProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}