// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.tensor

import com.google.protobuf.descriptor.FileDescriptorProto

object TensorProtoCompanion extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    org.tensorflow.framework.resource_handle.ResourceHandleProtoCompanion,
    org.tensorflow.framework.tensor_shape.TensorShapeProtoCompanion,
    org.tensorflow.framework.types.TypesProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      org.tensorflow.framework.tensor.TensorProto,
      org.tensorflow.framework.tensor.VariantTensorDataProto
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cgx0ZW5zb3IucHJvdG8SCnRlbnNvcmZsb3caFXJlc291cmNlX2hhbmRsZS5wcm90bxoSdGVuc29yX3NoYXBlLnByb3RvGgt0e
  XBlcy5wcm90byLXBwoLVGVuc29yUHJvdG8SNgoFZHR5cGUYASABKA4yFC50ZW5zb3JmbG93LkRhdGFUeXBlQgriPwcSBWR0eXBlU
  gVkdHlwZRJRCgx0ZW5zb3Jfc2hhcGUYAiABKAsyHC50ZW5zb3JmbG93LlRlbnNvclNoYXBlUHJvdG9CEOI/DRILdGVuc29yU2hhc
  GVSC3RlbnNvclNoYXBlEjkKDnZlcnNpb25fbnVtYmVyGAMgASgFQhLiPw8SDXZlcnNpb25OdW1iZXJSDXZlcnNpb25OdW1iZXISO
  QoOdGVuc29yX2NvbnRlbnQYBCABKAxCEuI/DxINdGVuc29yQ29udGVudFINdGVuc29yQ29udGVudBIpCghoYWxmX3ZhbBgNIAMoB
  UIOEAHiPwkSB2hhbGZWYWxSB2hhbGZWYWwSLAoJZmxvYXRfdmFsGAUgAygCQg8QAeI/ChIIZmxvYXRWYWxSCGZsb2F0VmFsEi8KC
  mRvdWJsZV92YWwYBiADKAFCEBAB4j8LEglkb3VibGVWYWxSCWRvdWJsZVZhbBImCgdpbnRfdmFsGAcgAygFQg0QAeI/CBIGaW50V
  mFsUgZpbnRWYWwSLQoKc3RyaW5nX3ZhbBgIIAMoDEIO4j8LEglzdHJpbmdWYWxSCXN0cmluZ1ZhbBI1CgxzY29tcGxleF92YWwYC
  SADKAJCEhAB4j8NEgtzY29tcGxleFZhbFILc2NvbXBsZXhWYWwSLAoJaW50NjRfdmFsGAogAygDQg8QAeI/ChIIaW50NjRWYWxSC
  GludDY0VmFsEikKCGJvb2xfdmFsGAsgAygIQg4QAeI/CRIHYm9vbFZhbFIHYm9vbFZhbBI1CgxkY29tcGxleF92YWwYDCADKAFCE
  hAB4j8NEgtkY29tcGxleFZhbFILZGNvbXBsZXhWYWwSZwoTcmVzb3VyY2VfaGFuZGxlX3ZhbBgOIAMoCzIfLnRlbnNvcmZsb3cuU
  mVzb3VyY2VIYW5kbGVQcm90b0IW4j8TEhFyZXNvdXJjZUhhbmRsZVZhbFIRcmVzb3VyY2VIYW5kbGVWYWwSVAoLdmFyaWFudF92Y
  WwYDyADKAsyIi50ZW5zb3JmbG93LlZhcmlhbnRUZW5zb3JEYXRhUHJvdG9CD+I/DBIKdmFyaWFudFZhbFIKdmFyaWFudFZhbBIvC
  gp1aW50MzJfdmFsGBAgAygNQhAQAeI/CxIJdWludDMyVmFsUgl1aW50MzJWYWwSLwoKdWludDY0X3ZhbBgRIAMoBEIQEAHiPwsSC
  XVpbnQ2NFZhbFIJdWludDY0VmFsIrABChZWYXJpYW50VGVuc29yRGF0YVByb3RvEioKCXR5cGVfbmFtZRgBIAEoCUIN4j8KEgh0e
  XBlTmFtZVIIdHlwZU5hbWUSKQoIbWV0YWRhdGEYAiABKAxCDeI/ChIIbWV0YWRhdGFSCG1ldGFkYXRhEj8KB3RlbnNvcnMYAyADK
  AsyFy50ZW5zb3JmbG93LlRlbnNvclByb3RvQgziPwkSB3RlbnNvcnNSB3RlbnNvcnNCbAoYb3JnLnRlbnNvcmZsb3cuZnJhbWV3b
  3JrQgxUZW5zb3JQcm90b3NQAVo9Z2l0aHViLmNvbS90ZW5zb3JmbG93L3RlbnNvcmZsb3cvdGVuc29yZmxvdy9nby9jb3JlL2ZyY
  W1ld29ya/gBAWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      org.tensorflow.framework.resource_handle.ResourceHandleProtoCompanion.javaDescriptor,
      org.tensorflow.framework.tensor_shape.TensorShapeProtoCompanion.javaDescriptor,
      org.tensorflow.framework.types.TypesProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}