// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.function

import com.google.protobuf.descriptor.FileDescriptorProto

object FunctionProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    org.tensorflow.framework.attr_value.AttrValueProto,
    org.tensorflow.framework.node_def.NodeDefProto,
    org.tensorflow.framework.op_def.OpDefProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      org.tensorflow.framework.function.FunctionDefLibrary,
      org.tensorflow.framework.function.FunctionDef,
      org.tensorflow.framework.function.GradientDef
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg5mdW5jdGlvbi5wcm90bxIKdGVuc29yZmxvdxoQYXR0cl92YWx1ZS5wcm90bxoObm9kZV9kZWYucHJvdG8aDG9wX2RlZi5wc
  m90byKcAQoSRnVuY3Rpb25EZWZMaWJyYXJ5EkIKCGZ1bmN0aW9uGAEgAygLMhcudGVuc29yZmxvdy5GdW5jdGlvbkRlZkIN4j8KE
  ghmdW5jdGlvblIIZnVuY3Rpb24SQgoIZ3JhZGllbnQYAiADKAsyFy50ZW5zb3JmbG93LkdyYWRpZW50RGVmQg3iPwoSCGdyYWRpZ
  W50UghncmFkaWVudCLGAwoLRnVuY3Rpb25EZWYSPwoJc2lnbmF0dXJlGAEgASgLMhEudGVuc29yZmxvdy5PcERlZkIO4j8LEglza
  WduYXR1cmVSCXNpZ25hdHVyZRJACgRhdHRyGAUgAygLMiEudGVuc29yZmxvdy5GdW5jdGlvbkRlZi5BdHRyRW50cnlCCeI/BhIEY
  XR0clIEYXR0chI8Cghub2RlX2RlZhgDIAMoCzITLnRlbnNvcmZsb3cuTm9kZURlZkIM4j8JEgdub2RlRGVmUgdub2RlRGVmEjwKA
  3JldBgEIAMoCzIgLnRlbnNvcmZsb3cuRnVuY3Rpb25EZWYuUmV0RW50cnlCCOI/BRIDcmV0UgNyZXQaZAoJQXR0ckVudHJ5EhoKA
  2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRI3CgV2YWx1ZRgCIAEoCzIVLnRlbnNvcmZsb3cuQXR0clZhbHVlQgriPwcSBXZhbHVlU
  gV2YWx1ZToCOAEaTAoIUmV0RW50cnkSGgoDa2V5GAEgASgJQgjiPwUSA2tleVIDa2V5EiAKBXZhbHVlGAIgASgJQgriPwcSBXZhb
  HVlUgV2YWx1ZToCOAFKBAgCEAMifQoLR3JhZGllbnREZWYSNgoNZnVuY3Rpb25fbmFtZRgBIAEoCUIR4j8OEgxmdW5jdGlvbk5hb
  WVSDGZ1bmN0aW9uTmFtZRI2Cg1ncmFkaWVudF9mdW5jGAIgASgJQhHiPw4SDGdyYWRpZW50RnVuY1IMZ3JhZGllbnRGdW5jQm4KG
  G9yZy50ZW5zb3JmbG93LmZyYW1ld29ya0IORnVuY3Rpb25Qcm90b3NQAVo9Z2l0aHViLmNvbS90ZW5zb3JmbG93L3RlbnNvcmZsb
  3cvdGVuc29yZmxvdy9nby9jb3JlL2ZyYW1ld29ya/gBAWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      org.tensorflow.framework.attr_value.AttrValueProto.javaDescriptor,
      org.tensorflow.framework.node_def.NodeDefProto.javaDescriptor,
      org.tensorflow.framework.op_def.OpDefProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}