// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.tensorflow.framework.function

/** GradientDef defines the gradient function of a function defined in
  * a function library.
  *
  * A gradient function g (specified by gradient_func) for a function f
  * (specified by function_name) must follow the following:
  *
  * The function 'f' must be a numerical function which takes N inputs
  * and produces M outputs. Its gradient function 'g', which is a
  * function taking N + M inputs and produces N outputs.
  *
  * I.e. if we have
  *    (y1, y2, ..., y_M) = f(x1, x2, ..., x_N),
  * then, g is
  *    (dL/dx1, dL/dx2, ..., dL/dx_N) = g(x1, x2, ..., x_N,
  *                                      dL/dy1, dL/dy2, ..., dL/dy_M),
  * where L is a scalar-value function of (x1, x2, ..., xN) (e.g., the
  * loss function). dL/dx_i is the partial derivative of L with respect
  * to x_i.
  *
  * @param functionName
  *   The function name.
  * @param gradientFunc
  *   The gradient function's name.
  */
@SerialVersionUID(0L)
final case class GradientDef(
    functionName: _root_.scala.Predef.String = "",
    gradientFunc: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[GradientDef] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = functionName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = gradientFunc
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = functionName
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = gradientFunc
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withFunctionName(__v: _root_.scala.Predef.String): GradientDef = copy(functionName = __v)
    def withGradientFunc(__v: _root_.scala.Predef.String): GradientDef = copy(gradientFunc = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = functionName
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = gradientFunc
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(functionName)
        case 2 => _root_.scalapb.descriptors.PString(gradientFunc)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = org.tensorflow.framework.function.GradientDef
    // @@protoc_insertion_point(GeneratedMessage[tensorflow.GradientDef])
}

object GradientDef extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.function.GradientDef] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.function.GradientDef] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.function.GradientDef = {
    var __functionName: _root_.scala.Predef.String = ""
    var __gradientFunc: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __functionName = _input__.readStringRequireUtf8()
        case 18 =>
          __gradientFunc = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.tensorflow.framework.function.GradientDef(
        functionName = __functionName,
        gradientFunc = __gradientFunc,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.function.GradientDef] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.tensorflow.framework.function.GradientDef(
        functionName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        gradientFunc = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = FunctionProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = FunctionProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.tensorflow.framework.function.GradientDef(
    functionName = "",
    gradientFunc = ""
  )
  implicit class GradientDefLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.function.GradientDef]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.function.GradientDef](_l) {
    def functionName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.functionName)((c_, f_) => c_.copy(functionName = f_))
    def gradientFunc: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.gradientFunc)((c_, f_) => c_.copy(gradientFunc = f_))
  }
  final val FUNCTION_NAME_FIELD_NUMBER = 1
  final val GRADIENT_FUNC_FIELD_NUMBER = 2
  def of(
    functionName: _root_.scala.Predef.String,
    gradientFunc: _root_.scala.Predef.String
  ): _root_.org.tensorflow.framework.function.GradientDef = _root_.org.tensorflow.framework.function.GradientDef(
    functionName,
    gradientFunc
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorflow.GradientDef])
}
